services:
  - type: web
    name: email-sorter-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: email-sorter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.playwright-browsers


databases:
  - name: email-sorter-db
    plan: free
    databaseName: email_sorter
    user: email_sorter_user