services:
  - type: web
    name: email-sorter-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y gcc postgresql-client libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2
      pip install -r requirements.txt
      pip install playwright
      PLAYWRIGHT_BROWSERS_PATH=/opt/render/.cache/ms-playwright playwright install chromium --with-deps
      alembic upgrade head && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: email-sorter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false


databases:
  - name: email-sorter-db
    plan: free
    databaseName: email_sorter
    user: email_sorter_user